# -*- coding: utf-8 -*-
"""nba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q6unj2CHysCgNbHwgWR7SrIcTW4rk6_D

# Analise de performance do jogador Ben Simmonds em relação ao pagamento recebido.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

players_salary = pd.read_excel('Salario.xlsx')

players_stats = pd.read_excel('2018-2019 NBA Player Stats  NBAstuffer.xlsx', header=1)

players_salary.head()

players_stats20 = pd.read_excel('2019-2020 NBA Player Stats  NBAstuffer.xlsx', header=1)

players20 = players_stats20.merge(players_salary, left_on='FULL NAME', right_on='Jogador', how='right')

players20.fillna(0, inplace=True)

players20 = players20.query('AGE > 0')

players = players_stats.merge(players_salary, left_on='FULL NAME', right_on='Jogador', how='right')

players.fillna(0, inplace=True)

players = players.query('AGE > 0')

"""## Checando a distribuição de Idade e Salário"""

sns.distplot(players.AGE)

sns.distplot(players.query('AGE <= 22.72').Salario)

"""# Referência 2018 -2019.

### Olhando os jogadores com média de idade menor que Ben Simmons
"""

players.query('AGE <= 22.72').Salario.describe().round()

bs = players.loc[players['FULL NAME'].str.contains('Ben Simmons')]
bs

"""### Comparando as Estatísticas do Ben Simmons com os demais jogadores da Liga

#### Jogadores que recebem a mesma faixa salarial do Ben Simmons
"""

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].PPG)
print(players[players["Salario"].between(8000000, 9000000, inclusive = True)].PPG.describe())

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].APG)
print(players[players["Salario"].between(8000000, 9000000, inclusive = True)].APG.describe())

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].MPG)
print(players[players["Salario"].between(8000000, 9000000, inclusive = True)].MPG.describe())

"""#### Jogadores que tem a mesma média de minutos por jogo, recebem quanto"""

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].Salario)
print(players[players["MPG"].between(30, 35, inclusive = True)].Salario.describe().round())

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].Salario)
print(players[players["AGE"].between(22, 23, inclusive = True)].Salario.describe().round())

"""#### Jogadores com o mesmo Defensive Rating"""

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].Salario)
print(players[players["DRTG"].between(102, 104, inclusive = True)].Salario.describe().round())

"""### Comparando Ben Simmons com os demais PG da liga"""

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].Salario)
print(players[players["Posição"] == " PG"].Salario.describe().round())

players['Posição'].value_counts()

point_guard = players.query('Posição == " PG"')

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].Salario)
print(point_guard[point_guard["DRTG"].between(102, 104, inclusive = True)].Salario.describe().round())

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].PPG)
print(point_guard[point_guard["Salario"].between(8000000, 9000000, inclusive = True)].PPG.describe())

print(players.loc[players['FULL NAME'].str.contains('Ben Simmons')].APG)
print(point_guard[point_guard["Salario"].between(8000000, 9000000, inclusive = True)].APG.describe())

bs20 = players.loc[players['FULL NAME'].str.contains('Ben Simmons')]

#sns.scatterplot(x=point_guard['Salario'], y=point_guard.PPG)
#sns.scatterplot(x=bs['Salario'], y=bs.PPG)
#sns.scatterplot(x=bs20['Salario'], y=bs20.PPG)

import plotly.graph_objects as go
fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['Salario'], y=point_guard.PPG,
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['Salario'], y=bs20.PPG,
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['Salario'], y=bs.PPG,
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['Salario'], y=point_guard.APG,
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['Salario'], y=bs20.APG,
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['Salario'], y=bs.APG,
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

#sns.scatterplot(x=point_guard['Salario'], y=point_guard.query("DRTG >0").DRTG)
#sns.scatterplot(x=bs['Salario'], y=bs.DRTG)

fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['Salario'], y=point_guard.query("DRTG >0").DRTG,
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['Salario'], y=bs20.DRTG,
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['Salario'], y=bs.DRTG,
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['Salario'], y=point_guard.query("DRTG >0").ORTG,
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['Salario'], y=bs20.ORTG,
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['Salario'], y=bs.ORTG,
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

#sns.scatterplot(x=point_guard['Salario'], y=point_guard['3P%'])
#sns.scatterplot(x=bs['Salario'], y=bs['3P%'])

fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['Salario'], y=point_guard.query("DRTG >0")['3P%'],
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['Salario'], y=bs20['3P%'],
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['Salario'], y=bs['3P%'],
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['Salario'], y=point_guard.query("DRTG >0")['3PA'],
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['Salario'], y=bs20['3PA'],
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['Salario'], y=bs['3PA'],
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=point_guard['3P%'], y=point_guard.query("DRTG >0")['3PA'],
                    mode='markers',
                    name='Point Guards', marker_size=5))

fig.add_trace(go.Scatter(x=bs20['3P%'], y=bs20['3PA'],
                    mode='markers',
                    name='Ben Simmons 18/19', marker_size=10))
fig.add_trace(go.Scatter(x=bs['3P%'], y=bs['3PA'],
                    mode='markers',
                    name='Ben Simmons 19/20', marker_size=10))


fig.show()

"""### Testando as correlações entre as variáveis escolhidas para Armador"""

sns.pairplot(point_guard)

ax = sns.heatmap(point_guard.corr(), linewidths=.5, cmap="YlGnBu", )
ax.figure.set_size_inches(16,8)
ax.set_title('Distribuição de Frequências - Recorrencia', fontsize = 18)
ax.set_xlabel('Metros', fontsize = 14)
ax

"""### Analisando o priemiro ano do Luka (gosto dele)"""

players20 = players_stats20.merge(players_salary, left_on='FULL NAME', right_on='Jogador', how='left')
players20

players20.loc[players20['FULL NAME'].str.contains('Luka Doncic')]

"""### Olhando a comparação do Ben vs os demais jogadfores da mesma posição

## Comparação especial Kristaps
"""

kp = players20.loc[players20['FULL NAME'].str.contains('Kristaps')]
bs20 = players20.loc[players20['FULL NAME'].str.contains('Ben Simmons')]

kp

power_foward = players.query('Posição == " PF"')

sns.scatterplot(x=power_foward['Salario'], y=power_foward.PPG)
sns.scatterplot(x=kp['Salario'], y=kp.PPG, facecolor='orange')
sns.scatterplot(x=bs20['Salario'], y=bs20.PPG, facecolor='yellow')

sns.scatterplot(x=power_foward['Salario'], y=power_foward.RPG)
sns.scatterplot(x=kp['Salario'], y=kp.RPG, facecolor='orange')
sns.scatterplot(x=bs20['Salario'], y=bs20.RPG, facecolor='yellow')

sns.scatterplot(x=power_foward['Salario'], y=power_foward.DRTG)
sns.scatterplot(x=kp['Salario'], y=kp.DRTG, facecolor='orange')
sns.scatterplot(x=bs20['Salario'], y=bs20.DRTG, facecolor='yellow')

sns.scatterplot(x=power_foward['Salario'], y=power_foward.ORTG)
sns.scatterplot(x=kp['Salario'], y=kp.ORTG, facecolor='orange')
sns.scatterplot(x=bs20['Salario'], y=bs20.ORTG, facecolor='yellow')

"""# Conclusão

Apesar de não possuir estatísticas para o arremesso de 3pt, o atleta analidado, Ben Simmons (76rs) tem um desempenho melhor do que os jogadores de sua posição que são pagos dentro da mesma faixa salarial. 
A diferença salarial vs o comparativo é mairo do que a diferença das estatísticas analisadas, incluindo idade e experiência.
"""



